[build-system]
build-backend = "setuptools.build_meta"
requires = ["wheel","setuptools"]

[project]
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: AnyIO",
    "Framework :: Trio",
    "Framework :: AsyncIO",
    "Programming Language :: Python :: 3",
    "Intended Audience :: Developers",
]
dependencies = []
keywords = ["MoaT"]
requires-python = ">=3.11"
name = "moat-lib-modbus"
maintainers = [{email = "matthias@urlichs.de", name = "Matthias Urlichs"}]
description = "Sans-IO Modbus protocol core (no pymodbus)"
readme = "README.rst"
authors = [{email = "matthias@urlichs.de", name = "Matthias Urlichs"}]
version = "0.1.0"

[project.urls]
homepage = "https://m-o-a-t.org"
repository = "https://github.com/M-o-a-T/moat"

[tool.setuptools]
[tool.setuptools.packages.find]
where = ["src"]
