#!/bin/bash

d=$(dirname $0)

while sleep 5 ; do ./mt -VVc local/thermo/test-pico.yaml micro run ; done &
while sleep 2 ; do ./mt -Vc local/thermo/ug-link.yaml micro run ; done &
while sleep 5 ; do $d/get-thermostat.py ; done &
