# See https://pre-commit.com for more information
#
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff
        args: [--fix, --show-fixes]
      - id: ruff-format
        exclude: "docs/.*"

  - repo: https://github.com/allganize/ty-pre-commit
    rev: v0.0.17
    hooks:
    - id: ty-check
      name: ty type checker
      description: Run ty type checker
      additional_dependencies:
      - pytest>=8.0
      - attrs

  - repo: local
    hooks:
    - id: check-yaml
      name: check yaml
      description: checks yaml files (understands MoaT tags)
      entry: pre_commit_hooks/check-yaml
      language: python
      types: [yaml]
      args: [--allow-multiple-documents]

    - id: pytest-modified
      name: pytest on modified modules
      description: runs pytest on test directories for modified moat modules
      entry: pre_commit_hooks/pytest
      language: python
      types: [python]
      pass_filenames: true
      require_serial: true

    - id: sphinx-build
      name: sphinx documentation build
      description: builds sphinx documentation and fails on warnings or errors
      entry: pre_commit_hooks/sphinx-build
      language: python
      pass_filenames: false
      files: "^(docs/.*|moat/.*\\.py)$"
