"""LabelTyp.Count

Revision ID: 795ad27fee3c
Revises: 0001
Create Date: 2025-03-06 15:48:51.109095+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '795ad27fee3c'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labeltyp', sa.Column('count', sa.Integer(), server_default='1', nullable=False, comment='Number of labels per sheet'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labeltyp', 'count')
    # ### end Alembic commands ###
