"""Boxes

Revision ID: 8b43dafb377a
Revises: 0fa6ecb8aec1
Create Date: 2025-03-04 08:50:46.168022+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b43dafb377a'
down_revision: Union[str, None] = '0fa6ecb8aec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boxtyp',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('boxtyp_tree',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['boxtyp.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['boxtyp.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_table('box',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('box')
    op.drop_table('boxtyp_tree')
    op.drop_table('boxtyp')
    # ### end Alembic commands ###
