"""Initial code per label type

Revision ID: 9ebac65fdfa3
Revises: af7e43cd35d8
Create Date: 2025-03-03 17:26:10.353913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ebac65fdfa3'
down_revision: Union[str, None] = 'af7e43cd35d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labeltyp', sa.Column('code', sa.Integer(), nullable=False, comment='Initial ID code when no labels exist', server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labeltyp', 'code')
    # ### end Alembic commands ###
