"""Init

Revision ID: af7e43cd35d8
Revises: 
Create Date: 2025-03-03 16:20:29.722766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7e43cd35d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labeltyp',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True, comment='URL prefix if the label has a random code element'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('label',
    sa.Column('code', sa.Integer(), nullable=False, comment='The numeric code in the primary barcode.'),
    sa.Column('rand', sa.String(), nullable=True, comment='random characters in the seconrady barcode URL.'),
    sa.Column('text', sa.String(), nullable=False, comment='The text on the label. May be numeric.'),
    sa.Column('typ_id', sa.Integer(), nullable=False),
    sa.Column('printed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['typ_id'], ['labeltyp.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('label')
    op.drop_table('labeltyp')
    # ### end Alembic commands ###
