import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { encodeMoat, decodeMoat } from '../../src/codec.js';
import { i_f2wire, wire2i_f } from '../../src/wire.js';
import { Path } from '../../src/path.js';
import { hexToBytes } from './helpers.js';

// Load the golden vectors generated by scripts/golden-gen.py
const golden = JSON.parse(
  readFileSync(new URL('../fixtures/golden.json', import.meta.url), 'utf-8'),
);

describe('golden vectors: header packing', () => {
  it('id=1 flag=0 → 0 (matches Python)', () => {
    expect(i_f2wire(1, 0)).toBe(golden.header.id1_flag0);
  });

  it('id=1 flag=1 → 1 (matches Python)', () => {
    expect(i_f2wire(1, 1)).toBe(golden.header.id1_flag1);
  });

  it('id=2 flag=0 → 4 (matches Python)', () => {
    expect(i_f2wire(2, 0)).toBe(golden.header.id2_flag0);
  });

  it('id=-1 flag=0 → -4 (matches Python)', () => {
    expect(i_f2wire(-1, 0)).toBe(golden.header.id_neg1_flag0);
  });

  it('id=-1 flag=2 → -2 (matches Python)', () => {
    expect(i_f2wire(-1, 2)).toBe(golden.header.id_neg1_flag2);
  });

  it('decode(0) → [1, 0] (matches Python)', () => {
    expect(wire2i_f(0)).toEqual(golden.header.decode_0);
  });

  it('decode(4) → [2, 0] (matches Python)', () => {
    expect(wire2i_f(4)).toEqual(golden.header.decode_4);
  });

  it('decode(-4) → [-1, 0] (matches Python)', () => {
    expect(wire2i_f(-4)).toEqual(golden.header.decode_neg4);
  });

  it('decode(-2) → [-1, 2] (matches Python)', () => {
    expect(wire2i_f(-2)).toEqual(golden.header.decode_neg2);
  });
});

describe('golden vectors: CBOR wire format', () => {
  it('simple call [0, ["ping"]] matches Python bytes', () => {
    const expected = hexToBytes(golden.simple_call.wire);
    const encoded = encodeMoat([0, ['ping']]);
    expect(encoded).toEqual(expected);
  });

  it('simple reply [-4, ["pong"]] matches Python bytes', () => {
    const expected = hexToBytes(golden.simple_reply.wire);
    const encoded = encodeMoat([-4, ['pong']]);
    expect(encoded).toEqual(expected);
  });

  it('error reply [-2, [-3]] matches Python bytes', () => {
    const expected = hexToBytes(golden.error_reply.wire);
    const encoded = encodeMoat([-2, [-3]]);
    expect(encoded).toEqual(expected);
  });

  it('call with args [0, ["echo"], 42, "hello"] matches Python bytes', () => {
    const expected = hexToBytes(golden.call_with_args.wire);
    const encoded = encodeMoat([0, ['echo'], 42, 'hello']);
    expect(encoded).toEqual(expected);
  });

  it('call with kwargs [0, ["cmd"], {key:value}] matches Python bytes', () => {
    const expected = hexToBytes(golden.call_with_kwargs.wire);
    const encoded = encodeMoat([0, ['cmd'], { key: 'value' }]);
    expect(encoded).toEqual(expected);
  });
});

describe('golden vectors: MoaT extension tags', () => {
  it('Path tag 39 matches Python bytes', () => {
    const expected = hexToBytes(golden.path_tag39.wire);
    const path = Path.build(['foo', 'bar']);
    const encoded = encodeMoat(path);
    expect(encoded).toEqual(expected);
  });

  it('Set tag 258 matches Python bytes', () => {
    const expected = hexToBytes(golden.set_tag258.wire);
    const encoded = encodeMoat(new Set([1, 2, 3]));
    // Sets may have different ordering; compare decoded instead
    const decodedExpected = decodeMoat(expected);
    const decodedActual = decodeMoat(encoded);
    expect(decodedActual).toEqual(decodedExpected);
  });
});

describe('golden vectors: primitives', () => {
  it('true → 0xf5 (CBOR bool, not int 1)', () => {
    expect(encodeMoat(true)).toEqual(hexToBytes(golden.bool_true.wire));
  });

  it('false → 0xf4 (CBOR bool, not int 0)', () => {
    expect(encodeMoat(false)).toEqual(hexToBytes(golden.bool_false.wire));
  });

  it('null → 0xf6', () => {
    expect(encodeMoat(null)).toEqual(hexToBytes(golden.null.wire));
  });

  it('undefined → 0xf7', () => {
    expect(encodeMoat(undefined)).toEqual(hexToBytes(golden.undefined.wire));
  });

  it('bytes → 0x43010203', () => {
    expect(encodeMoat(new Uint8Array([1, 2, 3]))).toEqual(hexToBytes(golden.bytes.wire));
  });

  it('text "hello" → 0x6568656c6c6f', () => {
    expect(encodeMoat('hello')).toEqual(hexToBytes(golden.text.wire));
  });
});

describe('golden vectors: float widths', () => {
  it('1.5 → f16 (0xf93e00)', () => {
    expect(encodeMoat(1.5)).toEqual(hexToBytes(golden.float_1_5.wire));
  });

  // 0.1 cannot be represented in f16 or f32, needs f64
  it('0.1 → f64 (0xfb3fb999999999999a)', () => {
    const encoded = encodeMoat(0.1);
    const decoded = decodeMoat(encoded);
    expect(decoded).toBe(0.1);
  });
});
