[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools-scm","wheel","setuptools"]

[project]
classifiers = ["Development Status :: 4 - Beta","License :: OSI Approved","Framework :: AnyIO","Framework :: Trio","Framework :: AsyncIO","Programming Language :: Python :: 3","Intended Audience :: Developers"]
dependencies = ["anyio ~= 3.0"]
dynamic = ["version"]
keywords = ["MoaT"]
requires-python = ">=3.8"
name = "moat-lib-pid"
maintainers = [{email = "matthias@urlichs.de",name = "Matthias Urlichs"}]
description='An advanced PID controller'
readme = "README.md"

[project.license]
file = "LICENSE.txt"

[project.urls]
homepage = "https://m-o-a-t.org"
repository = "https://github.com/M-o-a-T/moat-lib-pid"

[tool]
[tool.flake8]
max-line-length = 99
ignore = ["F841","F401","E731","E502","E402","E127","E123","E203","E231","W503","E501"]

[tool.isort]
line_length = 99
multi_line_output = 3
profile = "black"

[tool.setuptools_scm]

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py310,check

[testenv]
setenv = 
    PYTHONPATH = {env:PYTHONPATH}{:}{toxinidir}
deps = 
    trio
    pytest
commands = 
    python3 -mpytest tests/

[testenv:check]
commands = 
    pylint moat tests
    flake8p moat tests
    black --check moat tests
deps = 
    pytest
    pylint
    black
    flake8-pyproject
    flake8

"""

[tool.black]
line-length = 99

[tool.setuptools]
packages = ["moat.lib.pid"]
[tool.setuptools.package-data]
"*" = ["*.yaml"]

[tool.pylint]
[tool.pylint.messages_control]
disable = "wrong-import-order,use-dict-literal,unspecified-encoding,ungrouped-imports,too-many-statements,too-many-return-statements,too-many-nested-blocks,too-many-locals,too-many-instance-attributes,too-many-branches,too-many-arguments,too-few-public-methods,superfluous-parens,no-else-return,no-else-continue,invalid-name,fixme,line-too-long"

[tool.moat]
