#!/usr/bin/python3
"""
Checker for YAML with MoaT additions.
"""

from __future__ import annotations

import argparse

from moat.util import yload

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Generator, Sequence


def _exhaust(gen: Generator[str]) -> None:
    for _ in gen:
        pass


def main(argv: Sequence[str] | None = None) -> int:  # noqa:D103
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-m",
        "--multi",
        "--allow-multiple-documents",
        action="store_true",
    )
    parser.add_argument("filenames", nargs="*", help="Filenames to check.")
    args = parser.parse_args(argv)

    retval = 0
    for filename in args.filenames:
        try:
            with open(filename, encoding="UTF-8") as f:
                if args.multi:
                    for _ in yload(f, multi=True):
                        pass
                else:
                    yload(f)
        except Exception as exc:
            print(exc)
            retval = 1
    return retval


if __name__ == "__main__":
    raise SystemExit(main())
