link:
  backend_example:
    _doc: "Rename to 'backend'"
    typ: mqtt

    host: localhost
    user: foo
    pass: bar
    ssl:
      cert: '/path/to/cert.pem'
      key: '/path/to/cert.key'
  client:
    init_timeout: 5
  root: !P moat.test.unconfigured.update-me
  qos: 0

