system:
  capacity: 14
  batt_max_chg: 5
  batt_max_dis: 8
  inv_max_dis: 10
  inv_max_chg: 10
  buy_factor: 1.2
  buy_const: 0.24
  kwp: 10

  # position
  lat: 45.6
  long: 12.3
  # orientation
  degrees: 180
  azimuth: 0
sources:
  akumuli:
    host: localhost
    port: 8282
  forecast_solar:
    api-key: XXXXXXXXXXXXXXXX
    query:
      # see https://doc.forecast.solar/doku.php?id=api for possibilities
      damping: 1.0
solar:
  source: forefast_solar
price:
  source: akumuli
  series: price
  tags:
    type: power
per_hour: 1
