# basic BMS
# apps:
#   ser: serial.SerialCmd
#   batt: bms.rly1.BMSCmd

# ser:
#   uart: 0
#   tx: 0
#   rx: 1
#   baud: 2400
#   max:
#     len: 2000
#     idle: 500
#   start: 0xFF
#   # mark: 0x11
bat1:
  serial: ser
  batt:
    client: app.ems.rpy1.BMS
    server: moat.ems.battery.rpy1.BMS

    poll:
      t:
        # how often to poll, seconds
        voltage: 1000
        cellvoltage: 2000
        celltemperature: 5000
        live: 10000
      n:
        # report values after this many polls
        voltage: 5
    cap:
      a: 250  # actual capacity
      ah: 280  # nominal capacity
      loss: 0.02
      cur: 50000000  # actual battery capacity in watt seconds
      # a: 250  # time interval between measurements in msec
    n: 16  # number of cells in this battery

    # i|u.min|max trip the relay if they're exceeded.
    # i|u.ext.min|max values are communicated to external systems.
    #
    # What to do about voltage and current …
    u:
      max: 59
      min: 40.5
      ext:
        max: 57.28
        min: 41.5
    i:
      max: 200
      min: -200
      ext:
        max: 150
        min: -150

    # … and where to get them.
    power:
      client: moat.micro.part.combo.Multiply
      server: moat.ems.battery.link.Listen
      link: "u_i"
      sub:
      - u
      - i
      u:
        client: moat.micro.part.adc.ADC
        scale: 0.0013
        offset: 0
        pin: 26
        n: 5
        nn: 2
  
      i:
        client: moat.micro.part.combo.RelADC
        pin:
          client: moat.micro.part.adc.ADC
          pin: 27  # positive pin
          scale: -0.000125
          offset: 0.1
          n: 5
          nn: 2
        ref: 28  # negative pin

      t: 200  # msec
      n: 5    # number of reads until sending an update message

    balancer: {}
    relay:
      client: bms._relay.PinRelay
      pin: 2
      t: 10000  # time until re-engaging relay after an error
      t1: 2000  # as before but first switch
    cell:
      server: moat.ems.battery.bms.rpy1.SerialCells
      port: 0
      balance:
        min: 3.45
        d: 0.05
        n: 4
        r: 0.05
  
      # default settings for all cells
      u:
        min: 2.7
        max: 3.63
        nom: 3.2
        ext:
          min: 2.9
          max: 3.58
        lim:  # voltages where max current starts degrading
          min: 3.0
          max: 3.4
  
        # the values below are updated from the cell module
        scale: 0.001
        offset: 0
        samples: 5
        
        # area to consider for additional Umax leeway
        range: 0.5
        # the sum of our cell values may be a bit off
        corr: 0.985

      load:
        # load resistor
        r: 3.1
        # load thermistor max temperature
        max: 60
        b: 3950

      batt:
        # external (battery) thermistor
        b: 3950
        min: 15
        max: 45
  
      # individual overrides
      cells: {}

    # per-battery
    poll:
      # multiple U+I readings are averaged to decrease noise
      d: 2000 # additional delay until next poll

      # time until relay disconnects due to non-live-ness
      # needs to survive a controller restart
      k: 15000
