link:
  server:
    save:
      dir: "/var/lib/moat/link/data"
    timeout:
      monitor: 0.5
      refresh: 100
    standalone: true
    ping:
      cycle: 50
      gap: 5
    ports:
      main:
        host: 127.0.0.1
        port: 27587

