[build-system]
build-backend = "setuptools.build_meta"
requires = ["wheel","setuptools"]

[project]
name = "moat.signal"
version = "0.0.1"
description = "Python API client for signal-cli JSON-RPC"
authors = ["Stefan Heitmüller <stefan.heitmueller@gmx.com>"]
readme = "README.md"
repository = "https://github.com/M-o-a-T/moat"
license-files = ["LICENSE.txt"]
dependencies = [
    "requests ~= 2",
    "python-magic ~= 0.4",
    "jmespath ~= 1",
    "packaging ~= 23",
]

[project.urls]
homepage = "https://m-o-a-t.org"
repository = "https://github.com/M-o-a-T/moat"

[project.optional-dependencies]
dev = [
    "pytest ~= 8.0"
    "pook ~= 1.4"
    "pytest-cov ~= 4.1"
]
docs = [
    "furo ~= 2024.1.29",
    "sphinx-autobuild ~= 2024.2.4",
    "sphinx-copybutton ~= 0.5.2",
    "sphinx-inline-tabs ~= 2023.4.21",
]

[tool.setuptools]
packages = [ "moat.signal",]

[tool.setuptools.package-data]
"*" = ["*.yaml"]
