[tool.poetry]
name = "moat.signal"
version = "23.2.1"
description = "Python API client for signal-cli JSON-RPC"
authors = ["Stefan Heitmüller <stefan.heitmueller@gmx.com>"]
readme = "README.md"
repository = "https://gitlab.com/M-o-a-T/moat-signal"
# documentation = "https://pysignalclijsonrpc.readthedocs.io/"

[tool.poetry.dependencies]
python = "^3.9"
requests = "~2"
python-magic = "~0.4"
jmespath = "~1"
packaging = "~23"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pook = "^1.4.2"
pytest-cov = "^4.1.0"


[tool.poetry.group.docs.dependencies]
furo = "^2024.1.29"
sphinx-autobuild = "^2024.2.4"
sphinx-copybutton = "^0.5.2"
sphinx-inline-tabs = "^2023.4.21"

[tool.isort]
profile = "black"
src_paths = ["moat.signal"]

[tool.pytest.ini_options]
addopts = "--junitxml=pytest.xml --cov=moat.signal --cov-report=term-missing -v -W ignore::DeprecationWarning"
testpaths = [
  "tests",
]
pythonpath = [
  ".",
]

[tool.bandit.assert_used]
skips = ["tests/test_*.py"]

[build-system]
requires = [
  "poetry-core",
]
build-backend = "poetry.core.masonry.api"
