#!/bin/bash
set -ex

# This script starts up MoaT-Link.

if test ! -n "$NAME" ; then
    NAME="$(uname -n)"
fi

if test -v TEMP && test -s "$TEMP" ; then
    test -f /etc/moat/link.init && rm /etc/moat/link.init
    exec moat -c /etc/moat/moat.cfg link server -n "$NAME" -l "$TEMP"
elif test -f /etc/moat/link.init ; then
    D="$(head -1 /etc/moat/link.init)"
    rm /etc/moat/link.init
    exec moat -c /etc/moat/moat.cfg link server -n "$NAME" -I "$D"
else
    exec moat -c /etc/moat/moat.cfg link server -n "$NAME"
fi
