dev:
  sew:
    power: !P :mr.moat.sew.power
    state: !P :mr.moat.sew.state
    mqtt:
      codec: msgpack
      will:
        topic: !P :mr.moat.sew.state
        message: null
    modbus:
      port: "/dev/null"  # EDIT
      serial:
        baudrate: 19200
        parity: N
      unit: 1
