#!/bin/bash

# Usage: runner unixpipe cmd args…
# 

if test $# -lt 2 ; then
    echo Usage: $0 unixpipe cmd args…
    exit 1
fi

PN="$1"
shift
PID=

rm -f "$PN"
mkfifo "$PN"
while read a ; do
    if test "$a" == "T" ; then : test
    elif test "$a" == "R" ; then
        test -n "$PID" && kill "$PID"
        wait
        "$@" &
        PID=$!
    elif test "$a" == "K" ; then
        test -n "$PID" && kill "$PID"
        wait
        PID=
    fi
done < "$PN"

