#!/bin/bash

set -ex

if [ $# != 1 ] ; then
    echo "Usage: $0 cfg.file"
    exit 1
fi

if [ -x "./mt" ] ; then 
    M=./mt
    S=micro
    MPY=$S/lib/micropython
elif [ -x "../mt" ] ; then 
    M=../mt
    S=.
    MPY=$S/lib/micropython
else
    if test ! -v MPY ; then
        echo "Usage: MPY=/path/to/micropython $0 cfg.file"
        exit 1
    fi

    M=moat
fi

cfg="$1"

port=$($M -c "$cfg" util cfg micro.setup.r.port)
baud=$($M -c "$cfg" util cfg micro.setup.r.mode.rate)

dev=$($M -c "$cfg" util cfg micro.install.port)
rate=$($M -c "$cfg" util cfg micro.install.rate)

export MOAT_EMBED="$($M -c "$cfg" micro path)"

git submodule update --init
pushd $MPY

make -C ports/$dev submodules
make -C mpy-cross
cd ports/$dev
make -j ESPTOOL=esptool PORT=$port BAUD=$rate BOARD=${dev@U}_MOAT deploy

