#!/bin/bash

mkdir -p /run/moat-test
. "$(dirname "$0")/config.sh"

# Terminal? set window title
case "$TERM" in
	xterm*|rxvt*)
		echo -en "\e]0;Test $PILL\a"
		;;
esac

cd "$(dirname "$0")/.."
if [ "$CODE" = "gate" ] ; then
	P="./mb -vv gateway -u mqtt://$MQTT -p $DEV"
else
	P="miniterm $DEV 57600"
fi

bash -x ./utils/runner /run/moat-test/test_$PILL env PYTHONPATH=moat-bus $P
