#!/bin/bash

set -e
CFG="${CFG:-./cfg}"
. "$CFG/common"
PILLS="${PILLS:-a b c}"

D="$(dirname "$0")"
for t in $PILLS ; do
	if ! test -p /run/moat-test/test_$t ; then
		echo "'test $t' is not running. Exiting."
		exit 1
	fi
done

set -x
for t in $PILLS ; do
	echo K >/run/moat-test/test_$t
done
sleep 1

# XXX do this in parallel. Need to protect against failures.
for t in $PILLS ; do
	if "$D/prog" $t || "$D/prog" $t || "$D/prog" $t ; then : ; else
		echo "Programming Pill $t failed. Exiting." >&2; exit 1
	fi
done
#wait

for t in $PILLS ; do
	echo R >/run/moat-test/test_$t
done

sleep 3
for t in $PILLS ; do
	"$D/reset" $t
done
