[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools", "wheel",]

[project]
classifiers = [
	"Intended Audience :: Developers",
	"Programming Language :: Python :: 3",
	"Framework :: AsyncIO",
	"Framework :: Trio",
	"Framework :: AnyIO",
	"Development Status :: 4 - Beta",
	]
dependencies = [
	"anyio ~= 4.2",
	"asyncactor ~= 0.28.0",
	"asyncclick",
	"attrs",
	"ruyaml",
	"simpleeval",
	"moat-util ~= 0.62.2",
	"moat-lib-rpc ~= 0.5.1",
	"moat-lib-codec ~= 0.4.7",
	"moat-link ~= 0.2.46",
	"moat-lib-mqtt ~= 0.0.1",
	"moat-lib-config ~= 0.1.1",
	"moat-lib-broadcast ~= 0.1.2",
	]
version = "0.3.25"
keywords = [ "MoaT",]
requires-python = ">=3.8"
name = "moat-link-server"
description = "Storage for messages between MoaT instances"
readme = "README.rst"

[[project.authors]]
name = "Matthias Urlichs"
email = "matthias@urlichs.de"

[project.urls]
homepage = "https://m-o-a-t.org"
repository = "https://github.com/M-o-a-T/moat"

[tool.setuptools]
[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.yaml"]
