# Configuration file for the Sphinx documentation builder.
#
# This file, and some other templates of this documentation, started off as
# https://github.com/mhostetter/galois/blob/main/docs/
#
# SPDX-License-Identifier: MIT

# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html


# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc2) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
from __future__ import annotations

import os
import sys
from pathlib import Path

if Path("_static").exists():
    docs_dir = Path(".")
    sys.path.insert(0, os.path.abspath(".."))
else:
    docs_dir = Path("docs")
    sys.path.insert(0, os.path.abspath("."))

# get the current version
import subprocess

version = subprocess.check_output(["git", "describe"]).decode("utf-8").strip()

# Assign a build variable to the builtin module that inerts the @set_module decorator. This is done because set_module
# confuses Sphinx when parsing overloaded functions. When not building the documentation, the @set_module("moat")
# decorator works as intended.
import builtins

builtins.__sphinx_build__ = True

import sphinx

# Suppress specific sphinx-autodoc-typehints warnings
import warnings

warnings.filterwarnings(
    "ignore",
    message=r"Cannot resolve forward reference.*BroadcastReader.: name 'Broadcaster' is not defined..sphinx_autodoc_typehints.forward_reference.",
)

# -- Project information -----------------------------------------------------

project = "moat"
copyright = "2018-2026, Matthias Urlichs"
author = "Matthias Urlichs"
# version: see above


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named "sphinx.ext.*") or your custom
# ones.
extensions = [
    # "autodoc2",
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    # "sphinx.ext.mathjax",
    "sphinx.ext.intersphinx",
    "sphinx_last_updated_by_git",
    "sphinx_autodoc_typehints",
    "enum_tools.autoenum",
    "myst_parser",
    # "sphinx_immaterial",
    # "sphinx_immaterial.apidoc.python.apigen",
    # "sphinx_immaterial.theme_result",
    "sphinx_design",
    "sphinx_favicon",
    "sphinx_book_theme",
    "sphinx_tabs.tabs",
]
myst_enable_extensions = [
    "attrs_block",
    "colon_fence",
]

sd_custom_directives = {
    "dropdown-syntax": {
        "inherit": "dropdown",
        "argument": "Syntax",
        "options": {
            "color": "primary",
            "icon": "code",
        },
    }
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# Tell sphinx that ReadTheDocs will create an index.rst file as the main file,
# not the default of contents.rst.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", ".ipynb_checkpoints"]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_book_theme"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

html_css_files = [
    "basic.css",
    "extra.css",
]

# Define a custom inline Python syntax highlighting literal
rst_prolog = """
.. role:: python(code)
   :language: python
   :class: highlight
"""

# Sets the default role of `content` to :any:`content`, which creates cross-references
default_role = "py:obj"

favicons = [
    {"href": "MoaT-gears.svg"},  # => use `_static/icon.svg`
    {"href": "MoaT.16.png"},
    {"href": "MoaT.32.png"},
    {"href": "MoaT.64.png"},
    {"href": "MoaT.128.png"},
    {
        "rel": "apple-touch-icon",
        "href": "MoaT.180.png",
    },
]
html_title = "The Master of all Things"
html_logo = "_static/MoaT.svg"

# theme options
html_theme_options = {
    #   "icon": {
    #       "repo": "fontawesome/brands/github",
    #   },
    "globaltoc_collapse": False,
    "show_toc_level": 4,
    "toc_title": "Contents",
    "navigation_with_keys": True,
    "show_nav_level": 2,
}

html_sidebars = {"**": ["navbar-logo.html", "search-field.html", "sbt-sidebar-nav.html"]}

html_last_updated_fmt = ""
html_use_index = True
html_domain_indices = True


# -- Extension configuration -------------------------------------------------

# Create hyperlinks to other documentation
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "anyio": ("https://anyio.readthedocs.io/en/stable/", None),
    # "asyncdbus": ("https://M-o-a-T.org/docs/asyncdbus/", None),
    # "asyncclick": ("https://M-o-a-T.org/docs/asyncclick/", None),
    # "pyfuse3": ("https://M-o-a-T.org/docs/asyncclick/", None),
}

autodoc2_packages = [
    "../moat",
]
autodoc2_render_plugin = "rst"
autodoc2_output_dir = "api"
autodoc2_docstring_parser_regexes = [
    (r".*", "rst"),
]
autodoc2_skip_module_regexes = [
    r".*\.OFF\..*",
    r".*\._embed\..*",
]
autodoc2_hidden_objects = [
    "private",
    "inherited",
]

autodoc_default_options = {
    "members": True,
    # "special-members": True,
    # "inherited-members": True,
    # "member-order": "groupwise",
}
autodoc_typehints = "description"
autodoc_typehints_description_target = "documented"
autodoc_typehints_format = "short"

# Suppress warnings for forward references in TYPE_CHECKING blocks
typehints_fully_qualified = False
autodoc_inherit_docstrings = False
always_use_bars_union = True
typehints_defaults = "comma"

autodoc_type_aliases = {
    "moat.lib.gpio.gpio.Chip": "moat.lib.gpio.Chip",
    "moat.lib.rpc.base.BaseMsgHandler": "moat.lib.rpc.BaseMsgHandler",
    "moat.lib.rpc.base.Caller": "moat.lib.rpc.Caller",
    # "os.statvfs_result": "python.os.statvfs_result"
    # "RetainHandling": "moat.lib.mqtt.RetainHandling",
}
autoclass_content = "both"
autodoc_member_order = "groupwise"
nitpicky = True
nitpick_ignore = [
    ("py:class", "Sequence"),
    ("py:class", "Broadcaster"),
    ("py:class", "T"),
    ("py:class", "PathElem"),
    ("py:class", "moat.lib.repl.types.TypeAliasType"),
    ("py:obj", "moat.lib.broadcast._impl.TData"),
    ("py:obj", "NotGiven"),
    ("py:func", "moat.lib.path.Path.from_path"),
    ("py:class", "os.statvfs_result"),
    # TODO
    ("py:func", "asyncclick.command"),
    ("py:func", "asyncclick.group"),
    ("py:class", "asyncclick.core.Command"),
    ("py:class", "asyncclick.core.Group"),
    ("py:class", "asyncclick.Group"),
    ("py:class", "asyncdbus.service.ServiceInterface"),
    ("py:func", "pyfuse3.main"),
    ("py:obj", "pyfuse3.EntryAttributes"),
    ("py:obj", "pyfuse3.EntryAttributes.entry_timeout"),
    ("py:obj", "pyfuse3.StatvfsData"),
    ("py:obj", "pyfuse3.FileInfo"),
    ("py:obj", "pyfuse3.FileInfo.fh"),
    ("py:obj", "pyfuse3.FUSEError"),
    ("py:obj", "pyfuse3.RENAME_EXCHANGE"),
    ("py:obj", "pyfuse3.RENAME_NOREPLACE"),
    ("py:obj", "pyfuse3.EntryAttributes.st_ctime_ns"),
    ("py:meth", "pyfuse3.readdir_reply"),
    ("py:class","pyfuse3._pyfuse3.Operations"),
    ("py:class","pyfuse3.__init__.FileInfo"),
    ("py:class","pyfuse3.__init__.EntryAttributes"),
    ("py:class", "pyfuse3.__init__.StatvfsData"),
    ("py:func","pyfuse3.get_sup_groups"),
]
nitpick_ignore_regex = [
    (r".*", r"'Broadcaster'"),
]

# -- Sphinx Immaterial configs -------------------------------------------------

# Python apigen configuration
python_apigen_modules = {
    "moat": "api/moat.",
}
python_apigen_default_groups = [
    ("class:.*", "Classes"),
    ("data:.*", "Variables"),
    ("function:.*", "Functions"),
    ("classmethod:.*", "Class methods"),
    ("method:.*", "Methods"),
    (r"method:.*\.[A-Z][A-Za-z,_]*", "Constructors"),
    (r"method:.*\.__[A-Za-z,_]*__", "Special methods"),
    (r"method:.*\.__(init|new)__", "Constructors"),
    (r"method:.*\.__(str|repr)__", "String representation"),
    ("property:.*", "Properties"),
    (r".*:.*\.is_[a-z,_]*", "Attributes"),
]
python_apigen_default_order = [
    ("class:.*", 10),
    ("data:.*", 11),
    ("function:.*", 12),
    ("classmethod:.*", 40),
    ("method:.*", 50),
    (r"method:.*\.[A-Z][A-Za-z,_]*", 20),
    (r"method:.*\.__[A-Za-z,_]*__", 28),
    (r"method:.*\.__(init|new)__", 20),
    (r"method:.*\.__(str|repr)__", 30),
    ("property:.*", 60),
    (r".*:.*\.is_[a-z,_]*", 70),
]
python_apigen_order_tiebreaker = "alphabetical"
python_apigen_case_insensitive_filesystem = False
python_apigen_show_base_classes = True

# Python domain directive configuration
python_type_aliases = autodoc_type_aliases
python_module_names_to_strip_from_xrefs = ["collections.abc"]

# General API configuration
object_description_options = [
    ("py:.*", dict(include_rubrics_in_toc=True)),
]


# Custom autodoc-skip-member handler to honor :meta public: directive
def autodoc_skip_member(app, what, name, obj, skip, options):
    """Don't skip objects with ``:meta public:`` in their docstring."""
    docstring = getattr(obj, "__doc__", None)
    if docstring:
        if ":meta public:" in docstring:
            return False
        if ":meta private:" in docstring:
            return True

    # default behavior
    return skip


OFF_sphinx_immaterial_custom_admonitions = [
    {
        "name": "note",
        "title": "Note",
        "classes": ["collapsible"],
        "icon": "fontawesome/solid/pencil",
        "override": True,
    },
    {
        "name": "warning",
        "title": "Warning",
        "classes": ["collapsible"],
        "icon": "fontawesome/solid/exclamation",
        "override": True,
    },
    {
        "name": "info",
        "icon": "fontawesome/solid/circle-info",
        "override": True,
    },
    {
        "name": "tip",
        "icon": "fontawesome/regular/lightbulb",
        "override": True,
    },
    {
        "name": "abstract",
        "icon": "fontawesome/regular/file-lines",
        "override": True,
    },
    {
        "name": "important",
        "icon": "fontawesome/solid/bolt",
        "override": True,
    },
    {
        "name": "example",
        "icon": "fontawesome/solid/terminal",
        "override": True,
    },
    {
        "name": "quote",
        "icon": "fontawesome/solid/quote-left",
        "override": True,
    },
    {
        "name": "question",
        "title": "Question",
        "classes": ["collapsible"],
        "icon": "fontawesome/solid/question",
        "color": (108, 117, 125),  # --sd-color-secondary
        "override": True,
    },
    {
        "name": "seealso",
        "title": "See also",
        "classes": ["collapsible"],
        "icon": "fontawesome/solid/magnifying-glass",
        "color": (108, 117, 125),  # --sd-color-secondary
        "override": True,
    },
    {
        "name": "versionadded",
        "icon": "fontawesome/solid/code-commit",
        "override": True,
    },
    {
        "name": "versionchanged",
        "icon": "fontawesome/solid/code-branch",
        "override": True,
    },
    {
        # This needs to be defined here so the icon is available when referenced in _templates/base.html
        "name": "star",
        "icon": "fontawesome/regular/star",
        "color": (255, 233, 3),  # Gold
    },
    {
        "name": "nomenclature",
        "title": "Variable nomenclature",
        "classes": ["collapsible"],
        "icon": "fontawesome/solid/arrow-down-a-z",
        "color": (108, 117, 125),  # --sd-color-secondary
    },
    {
        "name": "fast-performance",
        "title": "Faster performance",
        "icon": "material/speedometer",
        "color": (47, 177, 112),  # Green: --md-code-hl-string-color
    },
    {
        "name": "slow-performance",
        "title": "Slower performance",
        "icon": "material/speedometer-slow",
        "color": (230, 105, 91),  # Red: --md-code-hl-number-color
    },
]


# -- Monkey-patching ---------------------------------------------------------

SPECIAL_MEMBERS = {
    "__init__",
    "__repr__",
    "__str__",
    "__int__",
    "__call__",
    "__len__",
    "__eq__",
}


# def autodoc_skip_member(app, what, name, obj, skip, options):
#    """
#    Instruct autodoc to skip members that are inherited from np.ndarray.
#    """
#    if skip:
#        # Continue skipping things Sphinx already wants to skip
#        return skip
#
#    if name in SPECIAL_MEMBERS:
#        # Don't skip members in "special-members"
#        return False
#
#    if name[0] == "_":
#        # For some reason we need to tell Sphinx to hide private members
#        return True
#
#    return skip


def autodoc_process_bases(app, name, obj, options, bases):
    """
    Remove private classes or mixin classes from documented class bases.
    """
    # Determine the bases to be removed
    remove_bases = []
    for base in bases:
        if base.__name__[0] == "_" or "Mixin" in base.__name__:
            remove_bases.append(base)

    # Remove from the bases list in-place
    for base in remove_bases:
        bases.remove(base)


def autodoc_process_signature(app, what, name, obj, options, signature, return_annotation):
    signature = modify_type_hints(signature)
    return_annotation = modify_type_hints(return_annotation)
    return signature, return_annotation


def modify_type_hints(signature):
    """
    Fix shortening numpy type annotations in string annotations created with
    `from __future__ import annotations` that Sphinx can't process before Python
    3.10.

    See https://github.com/jbms/sphinx-immaterial/issues/161
    """
    #   if signature:
    #       signature = re.sub(r"(?<!~)np\.", "~numpy.", signature)
    #       signature = re.sub(r"(?<!~)galois\.", "~galois.", signature)
    return signature


def monkey_patch_parse_see_also():
    """
    Use the NumPy docstring parsing of See Also sections for convenience. This automatically
    hyperlinks plaintext functions and methods.
    """
    # Add the special parsing method from NumpyDocstring
    method = sphinx.ext.napoleon.NumpyDocstring._parse_numpydoc_see_also_section
    sphinx.ext.napoleon.GoogleDocstring._parse_numpydoc_see_also_section = method

    def _parse_see_also_section(self, section: str):
        """Copied from NumpyDocstring._parse_see_also_section()."""
        lines = self._consume_to_next_section()

        # Added: strip whitespace from lines to satisfy _parse_numpydoc_see_also_section()
        for i in range(len(lines)):
            lines[i] = lines[i].strip()

        try:
            return self._parse_numpydoc_see_also_section(lines)
        except ValueError:
            return self._format_admonition("seealso", lines)

    sphinx.ext.napoleon.GoogleDocstring._parse_see_also_section = _parse_see_also_section


def gen_icons():
    src = docs_dir / "_static" / "MoaT.svg"
    for sz in (128, 160, 180, 256):
        dest = docs_dir / "_static" / f"MoaT.{sz}.png"
        if not dest.exists():
            subprocess.check_call(["inkscape", "-o", str(dest), "-w", str(sz), str(src)])

    src_ng = docs_dir / "_static" / "MoaT-gears.svg"
    for sz in (16, 32, 64):
        dest = docs_dir / "_static" / f"MoaT.{sz}.png"
        if not dest.exists():
            subprocess.check_call(["inkscape", "-o", str(dest), "-w", str(sz), str(src_ng)])


suppress_warnings = [
    "docutils",
    "sphinx_autodoc_typehints.forward_reference",  # Suppress all forward ref warnings
]


def setup(app):
    # monkey_patch_parse_see_also()
    app.connect("autodoc-skip-member", autodoc_skip_member)
    # app.connect("autodoc-process-bases", autodoc_process_bases)
    # app.connect("autodoc-process-signature", autodoc_process_signature)
    gen_icons()

    # These imports are required to prevent circular import nonsense for typing
    import moat

    if not moat.DOC:
        raise RuntimeError("NoDoc")
    import anyio
    import asyncclick.core
    import prometheus_client
    import tenacity
    import httpx
    import httpx_ws
    import h11
    import wsproto
    import moat.lib.mqtt._types
    import moat.lib.rpc
    import moat.link
    import moat.link.server
    import moat.lib.stream.anyio
    import moat.lib.repl.commands
    import moat.micro.cmd.tree.dir

    import typing

    typing.TYPE_CHECKING = True
