# This is the configuration template for an ESP port.
#
moat:
  micro:
    setup:
      args:
        config: !P cfg.r
      app:
        app: dir
        r:
          app: serial.Raw
          port: !P :@.moat.micro.config.serial.run
          mode:
            rate: &rs 115200
            dtr_flip: true
            rts_flip: true
            dtr_state: false
            rts_state: false
            dtr_rts: 0.1

      run:
        app:
          app: dir
          t:
            app: sub.Err
            retry: -1
            timeout: 1000
            cfg:
              app: net.tcp.Link
              host: !P :@.moat.micro.config.net.addr
              port: &moat_port 27589

          n:
            app: net.unix.Port
            port: !P :@.moat.micro.config.socket

      install:
        port: esp32
        board: !P :@.moat.micro.config.board
        build: !P :@.moat.micro.config.tempdir

        serial: !P :@.moat.micro.config.serial.config
        rate: 400000

    cfg:
      r:
        net: !P :@.moat.micro.config.net
        app:
          app: dir
          wdt:
            app: wdt.Cmd
            t: 5000
            hw: true
          repl:
            app: stdio.console
            keep: false
            repl: true
          n:
            app: net.tcp.Port
            host: !P :@.moat.micro.config.net.addr
            port: *moat_port
          s:
            app: _sys.Cmd
          c:
            app: cfg.Cmd
          f:
            app: fs.Cmd

    connect:
      app:
        app: dir
        r:
          app: net.unix.Link
          port: !P :@.moat.micro.config.socket

      remote: !P r.t
      terminal: !P repl.rw
      path:
        fs: !P f
        sys: !P s
        cfg: !P c

    run:
      app:
        app: dir
        t:
          app: net.tcp.Link
          host: !P :@.moat.micro.config.net.addr
          port: *moat_port

        n:
          app: net.unix.Port
          port: !P :@.moat.micro.config.socket
